name: linux-wheels

# on:
#   release:
#     types:
#       - published

on:
  pull_request:
  push:
    branches: [master]

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      shell: bash

    - uses: ./.github/workflows/actions/manylinux1_x86_64
    - name: copy manylinux wheels
      run: |
        mkdir dist
        cp wheelhouse/gsw*-manylinux1_x86_64.whl dist/

    - name: CheckFiles
      run: |
        ls dist
      shell: bash

    - name: Publish a Python distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_PASSWORD }}